name: build-pr
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: build
    timeout-minutes: 20
    env:
      JAVA_OPTS: -Xms15G -Xmx15G -Xss10M -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms15G -Xmx15G -Xss10M -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
    - uses: actions/checkout@v3.0.2
    - uses: coursier/cache-action@v6
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libidn2-0-dev
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: openjdk@21.0.2=tgz+https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz

    - name: Restore build state
      uses: actions/cache@v3
      with:
        path: |
          */target/*
          !*/target/scala-*/.*-fastopt
          !*/target/scala-*/native-test/*
          **/target/*
          !**/target/scala-*/.*-fastopt
          !**/target/scala-*/native-test/*
        key: ${{ runner.os }}-build-state-main
        restore-keys: |
          ${{ runner.os }}-build-state-main

    - name: Build JVM
      run: sbt '+kyoJVM/testQuick'

    - name: Build JS
      run: sbt '+kyoJS/testQuick'

    - name: Build Native
      run: sbt '+kyoNative/testQuick'